books.author=MeloDev

quarkus.log.category."io.quarkus".level=WARNING
quarkus.log.category."lab.melostudy".level=INFO
quarkus.banner.enabled=false

# Default profiles dev, test, prd
%dev.quarkus.log.console.level=DEBUG
%test.quarkus.log.console.level=TRACE
%prod.quarkus.log.console.level=SEVERE
%prod.books.author=MeloProd

# custom profile
%staging.books.author=MeloTest