# BD Schema management
## Strategy
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
## Scripts generation
### active both scripts generation
quarkus.hibernate-orm.scripts.generation=drop-and-create
### targets
quarkus.hibernate-orm.scripts.generation.create-target=create.sql
quarkus.hibernate-orm.scripts.generation.drop-target=drop.sql

# Jandex Index
quarkus.index-dependency.artist.group-id=lab.melostudy
quarkus.index-dependency.artist.artifact-id=02-artist-jdbc

quarkus.index-dependency.customer.group-id=lab.melostudy
quarkus.index-dependency.customer.artifact-id=02-customer-jpa